apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-todo-app
  template:
    metadata:
      labels:
        app: react-todo-app
    spec:
      containers:
      - name: react-todo-container
        image: pradeep051/react-todo-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-todo-service
spec:
  selector:
    app: react-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
